import { expect, test } from "@playwright/test";

test("iPad layout keeps camera sizing and cross-page tools independent", async ({ page }) => {
  await page.setViewportSize({ width: 1024, height: 768 });
  await page.goto("/");
  await page.getByRole("button", { name: "暂时跳过" }).click();
  await page.getByTitle("收起侧栏").click();
  await expect(page.locator(".app-shell")).toHaveClass(/sidebar-collapsed/);
  const script = page.getByLabel("台词窗口", { exact: true });
  const timer = page.getByLabel("计时器窗口", { exact: true });
  const camera = page.getByLabel("镜头窗口", { exact: true });
  const cameraBefore = await camera.boundingBox();
  const cameraResize = await page.getByTitle("调整镜头窗口大小").boundingBox();
  await page.mouse.move(cameraResize!.x + 10, cameraResize!.y + 10);
  await page.mouse.down();
  await page.mouse.move(cameraResize!.x - 80, cameraResize!.y - 60);
  await page.mouse.up();
  const cameraAfter = await camera.boundingBox();
  expect(cameraAfter!.width).toBeLessThan(cameraBefore!.width);
  expect(cameraAfter!.height).toBeLessThan(cameraBefore!.height);
  const timerSize = await timer.boundingBox();
  const resize = await script.getByTitle("调整台词窗口大小").boundingBox();
  await page.mouse.move(resize!.x + 10, resize!.y + 10);
  await page.mouse.down();
  await page.mouse.move(resize!.x - 60, resize!.y - 40);
  await page.mouse.up();
  expect((await timer.boundingBox())?.width).toBe(timerSize?.width);
  await page.getByRole("button", { name: "知识库", exact: true }).click();
  await expect(script).not.toBeVisible();
  await expect(timer).not.toBeVisible();
  await expect(page.getByLabel("练习工具栏窗口")).toBeVisible();
  await page.getByRole("button", { name: "台词", exact: true }).click();
  await page.getByRole("menuitemcheckbox", { name: "跨页面悬浮" }).click();
  await expect(script).toHaveClass(/is-floating/);
  await expect(timer).not.toBeVisible();
  await page.getByTitle("关闭选项").click();
  await page.getByRole("button", { name: "计时", exact: true }).click();
  await page.getByRole("menuitemcheckbox", { name: "跨页面悬浮" }).click();
  await expect(timer).toHaveClass(/is-floating/);
  await page.getByTitle("关闭选项").click();
  await page.getByRole("button", { name: "台词", exact: true }).click();
  await page.getByRole("menu", { name: "台词选项" }).getByRole("button", { name: "隐藏台词", exact: true }).click();
  await expect(script).not.toBeVisible();
  await expect(timer).toBeVisible();
  await page.getByTitle("关闭选项").click();
  await page.getByRole("button", { name: "计时", exact: true }).click();
  await page.getByTitle("增加目标时长").click();
  await expect(timer.getByRole("timer")).toHaveText("04:00");
  await page.getByTitle("关闭选项").click();
  await page.reload();
  await expect(page.locator(".app-shell")).toHaveClass(/sidebar-collapsed/);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "音频输出", exact: true }).click();
  await expect(page.getByRole("menu", { name: "音频输出选项" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test("practice starts only after scroll choice and shows body-only script", async ({ page, context }) => {
  await context.grantPermissions(["microphone", "camera"]);
  await page.goto("/");
  await page.getByRole("button", { name: "暂时跳过" }).click();
  await page.getByRole("button", { name: "开始练习", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByRole("button", { name: "匀速滚动", exact: true }).click();
  await page.getByRole("button", { name: "开始本轮", exact: true }).click();
  await expect(page.getByRole("button", { name: "结束练习", exact: true })).toBeVisible();
  await expect(page.getByLabel("台词正文").getByRole("button")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "语音跟随", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "知识库", exact: true }).click();
  await expect(page.getByRole("button", { name: "结束练习", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "结束练习", exact: true }).click();
  await expect(page.getByRole("heading", { name: "练习复盘", exact: true })).toBeVisible();
});
